{{-  if .Values.secrets}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nats-secrets
  annotations:
    image/tag: "{{.Values.version}}"
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  provider: aws
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: certs
      type: Opaque
      data:
{{- range $key, $value := .Values.secrets }}
      - objectName: {{ $key | quote}}
        key: {{ $value | quote }}
{{- end }}
  parameters:
    objects: |
{{- range $key, $value := .Values.secrets }}
      - objectName: {{ $key | quote }}
        objectType: "ssmparameter"
{{- end }}
{{- end }}