{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}
  {{- if .Values.hpa.annotations }}
  annotations:
    {{ toYaml .Values.hpa.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}
  minReplicas: {{ .Values.replicas | default "1"}}
  maxReplicas: {{ .Values.hpa.maxReplicas | default "6"}}
  {{- if .Values.hpa.behavior }}
  behavior:
    {{- toYaml .Values.hpa.behavior | indent 4 }}
  {{- end }}
  metrics:
  {{- if .Values.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.memory | default "70" }}
  {{- end }}
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpu | default "70"  }}
  {{- end }}
  {{- if .Values.hpa.customMetric }}
  - type: Object
    object:
      metric:
        name: {{ .Values.hpa.customMetric }}
      describedObject:
        apiVersion: v1
        kind: Service
        name: {{ .Values.hpa.customResource }}
      target:
        type: Value
        value: {{ .Values.hpa.customTarget | default "100" }}
  {{- end }}
{{- end }}
